// Generated by Apple Swift version 2.0 (swiftlang-700.0.59 clang-700.0.72)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"


/// 接口
SWIFT_PROTOCOL_NAMED("FSAdvertViewInterface")
@protocol FSAdvertViewInterface
- (void)previous;
- (void)next;
@end

@class UIPageControl;
@class NSCoder;
@class FSAdvertViewCell;
@class UIScrollView;
@protocol FSAdvertViewDelegate;


/// 广告轮播控件
SWIFT_CLASS_NAMED("FSAdvertView")
@interface FSAdvertView : UIView <FSAdvertViewInterface, UIScrollViewDelegate>
@property (nonatomic) UIPageControl * __null_unspecified pageCtrl;
@property (nonatomic, weak) id <FSAdvertViewDelegate> __null_unspecified delegate;
@property (nonatomic) BOOL autoPlay;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)updateConstraints;
- (FSAdvertViewCell * __null_unspecified)reuseCycleItemForIdentityString:(NSString * __nonnull)idstring;
- (void)reloadData;
- (void)next;
- (void)previous;
- (void)scrollViewDidEndDecelerating:(UIScrollView * __nonnull)scrollView;
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView * __nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * __nonnull)scrollView willDecelerate:(BOOL)decelerate;
@end


@interface FSAdvertView (SWIFT_EXTENSION(FSAdvertisementView))
@end


SWIFT_PROTOCOL_NAMED("FSAdvertViewCellInterface")
@protocol FSAdvertViewCellInterface
@end

@class UIEvent;
@class UITouch;

SWIFT_CLASS_NAMED("FSAdvertViewCell")
@interface FSAdvertViewCell : UIView <FSAdvertViewCellInterface>
@property (nonatomic, readonly) UIView * __nonnull contentView;
@property (nonatomic, readonly, copy) NSString * __nonnull identity;
- (nonnull instancetype)initWithIdstring:(NSString * __nonnull)idstring;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (UIView * __nullable)hitTest:(CGPoint)point withEvent:(UIEvent * __nullable)event;
- (void)touchesBegan:(NSSet<UITouch *> * __nonnull)touches withEvent:(UIEvent * __nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * __nullable)touches withEvent:(UIEvent * __nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * __nonnull)touches withEvent:(UIEvent * __nullable)event;
- (void)touchesMoved:(NSSet<UITouch *> * __nonnull)touches withEvent:(UIEvent * __nullable)event;
@end



SWIFT_PROTOCOL_NAMED("FSAdvertViewDelegate")
@protocol FSAdvertViewDelegate

/// 返回一共有多少个广告图
- (NSInteger)FSAdvertViewCount:(FSAdvertView * __null_unspecified)adcycle;

/// 返回第i个视窗
- (FSAdvertViewCell * __null_unspecified)FSAdvertViewForCell:(FSAdvertView * __null_unspecified)adcycle index:(NSInteger)index;
@optional

/// 点击第i个cell索引
- (void)FSAdvertForCellDidSelected:(FSAdvertView * __null_unspecified)adcycle index:(NSInteger)index;
@end

@class UIImageView;

SWIFT_CLASS_NAMED("FSAdvertViewImageCell")
@interface FSAdvertViewImageCell : FSAdvertViewCell
@property (nonatomic, readonly) UIImageView * __nonnull imageview;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


#pragma clang diagnostic pop
